services:
  - type: web
    name: pydefend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYDEFEND_SECRET
        generateValue: true
